#!/bin/bash

cd /home/pi/NetBeansProjects/Mbybc/ValidatePlatinum

file=temp
COUNTER=20

#Retry every hour for 20 times
until [  $COUNTER -lt 1 ]; do

 echo COUNTER $COUNTER >> $file

#
#Add date and introduction
#
echo "

" > $file
date > $file
echo "(Daily)
" >> $file
echo " *** The following inconsistencies were found in the Platinum Database ***" >> $file
echo "
" >> $file

#
#Run command to build report
#
#java -cp ./*:build/classes \
#mb/ValidatePlatinum -ap \
#>> $file

java -jar dist/validatePlatinum.jar >> $file
result=$?

#
#Add ending
#
echo "

 *** End ***" >> $file

#cat $file
 
#
#Send the mail
# Using the cat -v command to print control chars, which prevents the body from being
# attached as a MIME attachment. (The tr command is an alternative)
#
if [ $result -eq 0 ]; then
 cat -v $file | mail -s "Platinum validation report" \
 tfcloete@gmail.com \
 johan.bhmoss@gmail.com \
 manager@mbybc.co.za \
 liesl@mbybc.co.za
 exit 0

else
 echo Cron.daily error: $result, Counter: $COUNTER | mail -s "Platinum validation report" \
 tfcloete@gmail.com \

 echo PWD: $(pwd)
 echo Oooops! Error: $result
 echo Counter: $COUNTER
fi


#tr -cd '\10\11\12\15\40-\176' < $file | mail -s "Test using tr $file" tfcloete@gmail.com exports@aloeferoxafrica.com

sleep 1h
let COUNTER--
done








